import Head from 'next/head'
import { Inter } from 'next/font/google'
import {
	VStack,
	Text,
	Heading,
	HStack,
	SimpleGrid,
	Grid,
	GridItem,
	ButtonGroup,
	Button,
	Stack,
} from '@chakra-ui/react'
import MonsterImage from '../../public/components/MonsterImage'
import LndImg from '../../public/components/LndImg'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name='description' content='Generated by create next app' />
				<meta name='viewport' content='width=device-width, initial-scale=1' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<VStack flex={1} alignItems={'stretch'} as={'main'} spacing={4}>
				<LndImg />
				<VStack>
					<SimpleGrid columns={{ base: 2 }} columnGap={2}>
						<Button backgroundColor={'whiteAlpha.200'}>IOS</Button>
						<Button backgroundColor={'whiteAlpha.200'}>Android</Button>
					</SimpleGrid>
				</VStack>
			</VStack>
		</>
	)
}
